baseURL = "https://blog.dejavu.sk/"
languageCode = "en-us"
title = "tl;dr"

# Styles
theme = "beautifulhugo"

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsCodeFences = true

# Analytics
googleAnalytics = "UA-45795634-2"

# Comments
# disqusShortname = "blogdejavusk"

[params]
    subtitle = "Treat Me Mean, I need the Reputation"
    rss = true
    comments = true
    twitterName = "vzacnetago"
    githubName = "mgajdos"
    useChroma = true
    customCss = ["css/override.css"]

[Author]
    name = "Michal Gajdoš"
    email = "michal@dejavu.sk"
    twitter = "vzacnetago"
    github = "mgajdos"
    stackoverflow = "users/290799/michal-gajdos"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[related]
    threshold = 80
    includeNewer = true
    toLower = true

[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "tags"
    weight = 100
